name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "33 3 * * 0"

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    name: Run tests and code coverage
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install FFmpeg for integration tests
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Run Tests with Coverage
        run: poetry run pytest --cov=shuku --cov-report xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  type_check:
    name: Type checking
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Type Check
        run: poetry run mypy shuku

  lint:
    name: Lint with Ruff
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Check with Ruff
        run: poetry run ruff check shuku
