name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "31 2 * * 0"

jobs:
  test:
    name: Run tests and code coverage
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install FFmpeg for integration tests
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --all-extras
      - name: Run Tests with Coverage
        run: poetry run pytest --cov=shuku --cov-report xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  type_check:
    name: Type checking
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --all-extras
      - name: Type Check
        run: poetry run mypy shuku

  style_check:
    name: Style check with Black
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Black
        run: pip install black
      - name: Check code formatting with Black
        run: black --check shuku
